[package]
name = "ft-app"
version = "0.1.0"
edition.workspace = true

[dependencies]
ft-core = { path = "../core" }
serde = { version = "1", features = ["derive"] }
sha2 = "0.10"
rustls = { version = "0.23", default-features = false, features = ["ring", "std", "tls12", "logging"] }
tokio = { version = "1", features = ["net", "sync", "rt-multi-thread", "time"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "tls12", "logging"] }
